export const planteles = [
{ cct:"20EBD0001C", plantel:"Bachillerato Integral Comunitario de Guelatao de Juárez"},
{ cct:"20EBD0002B", plantel:"Bachillerato Integral Comunitario de Santa María Alotepec"},
{ cct:"20EBD0002BE", plantel:"Bachillerato Integral Comunitario Extensión San Isidro Huayápam"},
{ cct:"20EBD0003A", plantel:"Bachillerato Integral Comunitario de Eloxochitlán de Flores Magón"},
{ cct:"20EBD0004Z", plantel:"Bachillerato Integral Comunitario de Santa María Chimalapa"},
{ cct:"20EBD0005Z", plantel:"Bachillerato Integral Comunitario de Santiago Choápam"},
{ cct:"20EBD0006Y", plantel:"Bachillerato Integral Comunitario de San Cristóbal Lachirioag"},
{ cct:"20EBD0007X", plantel:"Bachillerato Integral Comunitario de Santiago Nuyoó"},
{ cct:"20EBD0008W", plantel:"Bachillerato Integral Comunitario de Santa María Nutío"},
{ cct:"20EBD0009V", plantel:"Bachillerato Integral Comunitario de Santiago Xochiltepec"},
{ cct:"20EBD0011J", plantel:"Bachillerato Ngu Niya Yanu Zacu Kjuabitsien"},
{ cct:"20EBD0012I", plantel:"Bachillerato Integral Comunitario de San Miguel Chimalapa"},
{ cct:"20EBD0013H", plantel:"Bachillerato Integral Comunitario de Santiago Xanica"},
{ cct:"20EBD0013HE", plantel:"Bachillerato Integral Comunitario Extensión Benito Juárez Pochutla"},
{ cct:"20EBD0014G", plantel:"Bachillerato Integral Comunitario de Jaltepec de Candoyoc"},
{ cct:"20EBD0015F", plantel:"Bachillerato Integral Comunitario de San Antonio Huitepec"},
{ cct:"20EBD0015FE", plantel:"Bachillerato Integral Comunitario Extensión Zaachila"},
{ cct:"20EBD0016E", plantel:"Bachillerato Integral Comunitario de Santo Domingo Tepuxtepec"},
{ cct:"20EBD0016EE", plantel:"Bachillerato Integral Comunitario Extensión Guevea"},
{ cct:"20EBD0017D", plantel:"Bachillerato Integral Comunitario de Santiago Lalopa"},
{ cct:"20EBD0018C", plantel:"Bachillerato Integral Comunitario de San Agustín Tlacotepec"},
{ cct:"20EBD0019B", plantel:"Bachillerato Integral Comunitario de Santa María Teopoxco"},
{ cct:"20EBD0020R", plantel:"Bachillerato Integral Comunitario de San Pedro Sochiápam"},
{ cct:"20EBD0021Q", plantel:"Bachillerato Integral Comunitario de Santiago Ixtlayutla"},
{ cct:"20EBD0022P", plantel:"Bachillerato Integral Comunitario de San José de las Flores"},
{ cct:"20EBD0022PE", plantel:"Bachillerato Integral Comunitario Extensión San Pedro Tulixtlahuaca"},
{ cct:"20EBD0023O", plantel:"Bachillerato Integral Comunitario de San Bartolomé Ayautla"},
{ cct:"20EBD0024N", plantel:"Bachillerato Integral Comunitario de Santiago Tetepec"},
{ cct:"20EBD0025M", plantel:"Bachillerato Integral Comunitario de San Martín Peras"},
{ cct:"20EBD0026L", plantel:"Bachillerato Integral Comunitario de San Andrés Solaga"},
{ cct:"20EBD0027K", plantel:"Bachillerato Integral Comunitario de Álvaro Obregón"},
{ cct:"20EBD0027KE", plantel:"Bachillerato Integral Comunitario Extensión Huamúchil"},
{ cct:"20EBD0028J", plantel:"Bachillerato Integral Comunitario de Santos Reyes Pápalo"},
{ cct:"20EBD0029I", plantel:"Bachillerato Integral Comunitario de Teotitlán del Valle"},
{ cct:"20EBD0029IE", plantel:"Bachillerato Integral Comunitario Extensión Santiago Matatlán"},
{ cct:"20EBD0030Y", plantel:"Bachillerato Integral Comunitario de San Jerónimo Nuchita"},
{ cct:"20EBD0030YE", plantel:"Bachillerato Integral Comunitario Extensión Santiago Cacaloxtepec"},
{ cct:"20EBD0031X", plantel:"Bachillerato Integral Comunitario de San Miguel Ahuehuetitlán"},
{ cct:"20EBD0031XE", plantel:"Bachillerato Integral Comunitario Extensión Calihualá"},
{ cct:"20EBD0032W", plantel:"Bachillerato Integral Comunitario de Santiago Ixtaltepec"},
{ cct:"20EBD0032WE", plantel:"Bachillerato Integral Comunitario Extensión Piedra Blanca"},
{ cct:"20EBD0033V", plantel:"Bachillerato Integral Comunitario de Lázaro Cárdenas"},
{ cct:"20EBD0034U", plantel:"Bachillerato Integral Comunitario de San Lorenzo Cuaunecuiltitla"},
{ cct:"20EBD0034UE", plantel:"Bachillerato Integral Comunitario Extensión Vista Hermosa"},
{ cct:"20EBD0035T", plantel:"Bachillerato Integral Comunitario de San Vicente Coatlán"},
{ cct:"20EBD0035TE", plantel:"Bachillerato Integral Comunitario Extensión San Luis Amatlán"},
{ cct:"20EBD0036S", plantel:"Bachillerato Integral Comunitario de El Carrizal"},
{ cct:"20EBD0037R", plantel:"Bachillerato Integral Comunitario de Llano Víbora"},
{ cct:"20EBD0038Q", plantel:"Bachillerato Integral Comunitario de Arroyo Súchil"},
{ cct:"20EBD0038QE", plantel:"Bachillerato Integral Comunitario Extensión Los Ciruelos"},
{ cct:"20EBD0039P", plantel:"Bachillerato Integral Comunitario de Santa María Temaxcalapa"},
{ cct:"20EBD0040E", plantel:"Bachillerato Musical Comunitario de San Bartolomé Zoogocho"},
{ cct:"20EBD0040EE", plantel:"Bachillerato Integral Comunitario Extensión San Melchor Betaza"},
{ cct:"20EBD0041D", plantel:"Bachillerato Integral Comunitario de Benito Juárez"},
{ cct:"20EBD0041DE", plantel:"Bachillerato Integral Comunitario Extensión El Jícaro"},
{ cct:"20EBD0042C", plantel:"Bachillerato Integral Comunitario de El Gachupín"},
{ cct:"20EBD0042CE", plantel:"Bachillerato Integral Comunitario Extensión Santo Tomás Mazaltepec"},
{ cct:"20EBD0043B", plantel:"Bachillerato Integral Comunitario de La Blanca"},
{ cct:"20EBD0043BE", plantel:"Bachillerato Integral Comunitario Extensión San Francisco del Mar"},
{ cct:"20EBD0044A", plantel:"Bachillerato Integral Comunitario de Santa María Yaviche"},
{ cct:"20EBD0045Z", plantel:"Bachillerato Integral Comunitario de San Pedro Ñumí"},
{ cct:"20EBD0046Z", plantel:"Bachillerato Integral Comunitario de Coatecas Altas"},
{ cct:"20EBD0046ZE", plantel:"Bachillerato Integral Comunitario Extensión San Francisco Logueche"},
{ cct:"20EBD0047Y", plantel:"Bachillerato Integral Comunitario de La Ventosa"},
{ cct:"20EBD0047YE", plantel:"Bachillerato Integral Comunitario Extensión Juchitán"},
{ cct:"20EBD0048X", plantel:"Bachillerato Integral Comunitario de Aquiles Serdán"},
{ cct:"20EBD0049W", plantel:"Bachillerato Integral Comunitario de San Miguel Lachixola"},
{ cct:"20EBD0049WE", plantel:"Bachillerato Integral Comunitario Extensión San Pedro Ozumacín"}
];
